
SRCS= ../inner_parser/argument_parser.c ../inner_parser/argument_parser_str_list.c \
../inner_parser/argument_parser_utils.c \
../common_util.c ../builtin/ft_cd.c

LIBFT=../libft/libftprintf.a

test:
	cc test.c $(SRCS) $(LIBFT) -lreadline