
SRCS= ../inner_parser/argument_parser.c ../inner_parser/argument_parser_str_list.c \
../inner_parser/argument_parser_utils.c \
 ../builtin/ft_cd.c ../utils/common_util.c ../utils/error_exit.c ../utils/error_msg.c \
./process_command.c
LIBFT=../libft/libftprintf.a


#test:
#	cc test.c $(SRCS) $(LIBFT) -lreadline

test:
	cc test.c ../utils/error_exit.c ../utils/error_msg.c $(LIBFT)