SRCS= ft_echo.c ../inner_parser/argument_parser.c ../inner_parser/argument_parser_str_list.c \
../inner_parser/argument_parser_utils.c \
../common_util.c

all:
	cc -g $(SRCS) ../libft/libftprintf.a -lreadline
